// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHgEgyIaSdSnnM6ROkY94vmtZ5OXyfXnE',
    appId: '1:511515062753:web:e491aaf3fda58ec47922a0',
    messagingSenderId: '511515062753',
    projectId: 'project-c4471',
    authDomain: 'project-c4471.firebaseapp.com',
    storageBucket: 'project-c4471.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKe_mN_dbwyiQhpL-yDxW5xFekmOAwgA8',
    appId: '1:511515062753:android:5f2853990fe4403e7922a0',
    messagingSenderId: '511515062753',
    projectId: 'project-c4471',
    storageBucket: 'project-c4471.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJMkMAdf4GMo-4IDMOk79Aa1zRbSbOjKw',
    appId: '1:511515062753:ios:6298c5aa3509e73e7922a0',
    messagingSenderId: '511515062753',
    projectId: 'project-c4471',
    storageBucket: 'project-c4471.appspot.com',
    iosBundleId: 'com.example.flutterProjectMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJMkMAdf4GMo-4IDMOk79Aa1zRbSbOjKw',
    appId: '1:511515062753:ios:6298c5aa3509e73e7922a0',
    messagingSenderId: '511515062753',
    projectId: 'project-c4471',
    storageBucket: 'project-c4471.appspot.com',
    iosBundleId: 'com.example.flutterProjectMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHgEgyIaSdSnnM6ROkY94vmtZ5OXyfXnE',
    appId: '1:511515062753:web:55fdad5a8058d2577922a0',
    messagingSenderId: '511515062753',
    projectId: 'project-c4471',
    authDomain: 'project-c4471.firebaseapp.com',
    storageBucket: 'project-c4471.appspot.com',
  );
}
